spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      #hibernate.connection.provider_disables_autocommit: true
      #hibernate.cache.use_second_level_cache: true
      #hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#server:
#  servlet:
#    session:
#      cookie:
#        http-only: true
jwt:
  secret: OTdkNDJiYjI5OGFlNzAwOTMwYzliMmViYjBlMDA1MDc3YjVlMWE4NWRiZGViZjEwZjU2YjM1ZWNmZjRlNTBiNTdmMTM0ZmExN2YyZjdjZTYyNmE4MjMwYjA3MWZmODAzMTM2ODA0MjA3YTE0MDI0MDJjODg4MjdiNDA1ZmIzZTM
